
import { 
    Home, 
    LayoutDashboard, 
    Settings, 
    UserCircle, 
    LogOut, 
    Sun, 
    Moon, 
    File, 
    Folder, 
    ChevronLeft, 
    ChevronRight, 
    FileArchive, 
    Github,
    Rocket,
    Users,
    BarChart2,
    Zap,
    Loader2,
    type LucideProps
} from 'lucide-react';

export const Icons = {
    Home: (props: LucideProps) => <Home className="icon" {...props} />,
    Dashboard: (props: LucideProps) => <LayoutDashboard className="icon" {...props} />,
    Settings: (props: LucideProps) => <Settings className="icon" {...props} />,
    Profile: (props: LucideProps) => <UserCircle className="icon" {...props} />,
    Logout: (props: LucideProps) => <LogOut className="icon" {...props} />,
    Sun: (props: LucideProps) => <Sun className="icon" {...props} />,
    Moon: (props: LucideProps) => <Moon className="icon" {...props} />,
    File: (props: LucideProps) => <File className="icon" {...props} />,
    Folder: (props: LucideProps) => <Folder className="icon" {...props} />,
    ChevronLeft: (props: LucideProps) => <ChevronLeft className="icon" {...props} />,
    ChevronRight: (props: LucideProps) => <ChevronRight className="icon" {...props} />,
    Archive: (props: LucideProps) => <FileArchive className="icon" {...props} />,
    GitHub: (props: LucideProps) => <Github className="icon" {...props} />,
    Projects: (props: LucideProps) => <Rocket className="icon" {...props} />,
    Users: (props: LucideProps) => <Users className="icon" {...props} />,
    Server: (props: LucideProps) => <Zap className="icon" {...props} />,
    API: (props: LucideProps) => <BarChart2 className="icon" {...props} />,
    Loader: (props: LucideProps) => <Loader2 className="icon" {...props} />,
};
